### ISSUE TITLE
Azure/GCP Docs

### ISSUE THREAD

**Issue by tiny-dancer** [gruntwork-io/module-security-public#2]
The gruntworks website claims this module is also supported for azure and gcp however the documentation is specific to AWS.  is this intentional?

**Comment by brikis98** [comment]
Hi @tiny-dancer! Some of the modules in `module-security` work across multiple clouds, such as `auto-update`, `fail2ban`, `ntp`, `os-hardening`, and `tls-cert-private`. Of course, all the IAM specific modules are for AWS only.

**Comment by brikis98** [comment]
BTW, we hope to add much more complete support for Azure and GCP in the future for all of our modules. But it takes a tremendous amount of time to build these out, so our approach is to do it incrementally, building out specific modules for specific clouds as requested by customers.

**Comment by tiny-dancer** [comment]
ah, makes sense. thanks for the quick reply!

@brikis98, also wanted to mention your talk [How to Build Reusable, Composable, Battle tested Terraform Modules](https://www.youtube.com/watch?v=LVgP63BkhKQ) was excellent! It's being added to our terraform team's on-boarding material :) 👍

**Comment by brikis98** [comment]
That's great to hear! :)
